Shiftbook/Models/Tag.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shiftbook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tag()
        {
            this.TagsTasks = new HashSet<TagsTask>();
            this.WorkOrders = new HashSet<WorkOrder>();
        }
    
        public int Id { get; set; }
        public string TagName { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TagsTask> TagsTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
    }
}

Shiftbook/Controllers/TagsController.cs
using Shiftbook.BL;
using Shiftbook.Helping_Classes;
using Shiftbook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shiftbook.Controllers
{
    public class TagsController : Controller
    {
        DatabaseEntities db = new DatabaseEntities();
        GeneralPurpose gp = new GeneralPurpose();
        MailSender ms = new MailSender();
        // GET: Task

        private bool isLogedIn()
        {
            if (gp.ValidateLoggedinUser() != null)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        [Route("ViewTags")]
        // GET: Type
        public ActionResult ViewTags(string message = "", string color = "")
        {
            if (color == "red")
            {
                ViewBag.errormessage = message;
                ViewBag.color = color;
            }
            if (color == "green")
            {
                ViewBag.successfullmessage = message;
                ViewBag.color = color;
            }
            return View();
        }

        [HttpPost]
        public ActionResult GetTagList()
        {
            List<Tag> list = new List<Tag>();
            
            list = new TagsBL().GetActiveTagsList(db).OrderByDescending(x => x.Id).ToList();
            

            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string searchValue = Request["search[value]"];
            string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            string sortDirection = Request["order[0][dir]"];

            if (sortColumnName != "" && sortColumnName != null)
            {
                if (sortDirection == "asc")
                {
                    list = list.OrderByDescending(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                }
                else
                {
                    list = list.OrderBy(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                }
            }

            if (!string.IsNullOrEmpty(searchValue))
            {
                list = list.Where(x => x.TagName.ToLower().Contains(searchValue.ToLower())
                        ).ToList();
            }
            int totalrows = list.Count();
            int totalrowsafterfilterinig = list.Count();
            list = list.Skip(start).Take(length).ToList();

            List<DTO> udto = new List<DTO>();
            foreach (Tag u in list)
            {
                DTO obj = new DTO()
                {
                    TagId = u.Id,
                    TagEncId = GeneralPurpose.EncryptId(u.Id),
                    TagName = u.TagName,
                    Role = (int)gp.ValidateLoggedinUser().Role

                };

                udto.Add(obj);
            }
            return Json(new { data = udto, draw = Request["draw"], recordsTotal = totalrows, recordsFiltered = totalrowsafterfilterinig }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PostAddNewTag(Tag _tag, int PageId = -1)
        {
            if ((!isLogedIn()))
            {
                return RedirectToAction("Login", "Auth");
            }
            if (_tag.TagName == null)
            {
                if (PageId == 2)
                {
                    return RedirectToAction("NewInventory", "Inventory", new { message = "Fill all The <strong>(*)</strong> Fields", color = "red" });
                }
                else
                {
                    return RedirectToAction("ViewTags", new { message = "Fill all The <strong>(*)</strong> Fields", color = "red" });
                }
            }
            int count = new TagsBL().GetActiveTagsList(db).Where(x => x.TagName == _tag.TagName).Count();
            if (count > 0)
            {
                if (PageId == 2)
                {
                    return RedirectToAction("NewInventory", "Inventory", new { message = "This Name is Already Registered", color = "red" });
                }
                else
                {
                    return RedirectToAction("ViewTags", new { message = "This Name is Already Registered", color = "red" });
                }
            }

            Tag tag = new Tag()
            {
                TagName = _tag.TagName,
                IsActive = 1,
                CreatedAt = GeneralPurpose.DateTimeNow(),
            };
            if (new TagsBL().AddTag(tag, db))
            {
                if (PageId == 2)
                {
                    return RedirectToAction("NewInventory", "Inventory", new { message = "Record is Added Successfully", color = "green" });
                }
                else
                {
                    return RedirectToAction("ViewTags", new { message = "Record is Added Successfully", color = "green" });
                }
            }
            if (PageId == 2)
            {
                return RedirectToAction("NewInventory", "Inventory", new { message = "Record connot be added to database", color = "red" });
            }
            else
            {
                return RedirectToAction("ViewTags", new { message = "Record connot be added to database", color = "red" });
            }
        }

        [HttpPost]
        public ActionResult TagById(int Id = -1)
        {
            Tag _tag = new TagsBL().GetActiveTagById(Id, db);
            if (_tag != null)
            {
                Tag sST = new Tag()
                {
                    Id = _tag.Id,
                    TagName = _tag.TagName,
                };
                return Json(sST, JsonRequestBehavior.AllowGet);
            }

            return Json(JsonRequestBehavior.AllowGet);
        }

        public ActionResult PostUpdate(Tag _tag)
        {
            int count = new TagsBL().GetActiveTagsList(db).Where(x => x.TagName == _tag.TagName && x.Id != _tag.Id).Count();
            if (count > 0)
            {
                return RedirectToAction("ViewTags", new { message = "This Name is Already Registered", color = "red" });
            }
            Tag obj = new TagsBL().GetActiveTagById(_tag.Id, db);

            obj.TagName = _tag.TagName;

            if (new TagsBL().UpdateTag(obj, db))
            {
                return RedirectToAction("ViewTags", new { message = "Record is Updated Successfully", color = "green" });
            }

            return RedirectToAction("ViewTags", new { message = "Something is Wrong", color = "red" });
        }

        public ActionResult Delete(int id, string way = "")
        {
            Tag u = new TagsBL().GetActiveTagById(id, db);
            if (u == null)
            {
                return RedirectToAction("ViewTags", new { msg = "Record not found", color = "red", way = way });
            }

            List<TagsTask> tagsTask = new TagsTaskBL().GetActiveTagsTaskList(db).Where(x => x.TagsId == id).ToList();
            if(tagsTask.Count() >= 1)
            {
                foreach(var del in tagsTask)
                {
                    new TagsTaskBL().DeleteTagTask(del.Id, db);
                }
            }
            if (new TagsBL().DeleteTag(id, db))
            {
                return RedirectToAction("ViewTags", new { msg = "Record deleted successfully", color = "green", way = way });
            }
            else
            {
                return RedirectToAction("ViewTags", new { msg = "Something is wrong", color = "red", way = way });
            }
        }

    }
}

Shiftbook/Views/Tags/ViewTags.cshtml
@{
    ViewBag.Title = "PendingTasks";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


<style>
    .table > tbody > tr > td {
        padding: 5px !important;
    }
</style>

<img id="loadImg" src='../Content/assets/images/loading.gif' width='150' style="position:fixed; margin-top:20%; margin-left:35%; z-index:111; display:none" />

<!--Add New Modal-->
<div class="modal fade" id="AddNewModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Add New Tag</h3>
            </div>
            <form method="post" action="@Url.Action("PostAddNewTag", "Tags")">
                <div class="modal-body p-5">
                    <div class="col-md-12  m-10">
                        <div class="form-group">
                            <label class="control-label col-md-3 text-bold">Name <span class="text-danger">*</span></label>
                            <div class="col-md-9">
                                <input type="text" name="TagName" class="form-control required" required="" placeholder="Electrical">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer pt-10">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit Form</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Modal-->
<div class="modal fade" id="DeleteModal">
    <div class="modal-dialog">
        <div class="modal-content text-center">
            <div class="modal-header bg-danger">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Warning</h3>
            </div>
            <form method="post" action="@Url.Action("Delete", "Tags")">
                <div class="modal-body p-5">
                    <h6 class="text-semibold">
                        Do you really want to Delete this Tag?<br />
                        This will be deleted permanently from our system.
                    </h6>
                    <input type="hidden" name="id" id="TagDeleteId" />
                </div>
                <div class="modal-footer border-top-1 border-top-grey-800 pt-10">
                    <button type="button" class="btn btn-link" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Update Modal-->
<div class="modal fade" id="UpdateModal">
    <div class="modal-dialog">
        <div class="modal-content text-center">
            <div class="modal-header bg-success">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Update</h3>
            </div>
            <form method="post" action="@Url.Action("PostUpdate", "Tags")">
                <div class="modal-body p-5">
                    <div class="col-md-12  m-10">
                        <input type="hidden" name="Id" id="updId" value="" />
                        <div class="form-group">
                            <label class="control-label col-md-3 text-bold">Name <span class="text-danger">*</span></label>
                            <div class="col-md-9">
                                <input type="text" name="TagName" id="updName" class="form-control required" required="required" placeholder="Electrical">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer pt-10">
                    <button type="button" class="btn btn-link" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-success">Submit Form</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Form Modal-->
<!-- row -->
<div class="row row-sm ">
    <div class="row">
        <div class="col-lg-6 col-md-offset-3" id="ViewBagMessages">
            @if (ViewBag.successfullmessage != "" && ViewBag.successfullmessage != null)
            {
                <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
                    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
                    <span class="text-semibold">Complete!</span> @ViewBag.successfullmessage.
                </div>
            }
            @if (ViewBag.errormessage != "" && ViewBag.errormessage != null)
            {
                <div class="alert alert-danger alert-styled-left alert-bordered">
                    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
                    <span class="text-semibold">Oh snap!</span> @ViewBag.errormessage <span class="alert-link">try submitting again</span>.
                </div>
            }
        </div>
    </div>

    <!--div-->
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-header pb-0 pt-10">
                <div class="d-flex text-center">
                    <h1 class=""><u>Tag List</u></h1>
                    <i class="mdi mdi-dots-horizontal text-gray"></i>
                    <div class="row pt-20 ml-5 mr-5">
                        <div class="col-md-9 col-sm-6">
                            &nbsp;
                        </div>
                        <div class="col-md-2 col-sm-6 pull-right">
                            <button class="btn btn-primary btn-block" onclick="AddNew()">Add New Tag</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table text-md-nowrap table-striped table-bordered text-center" id="TagTable">
                        <thead class="bg-purple">
                            <tr>
                                <th class="text-center">Action</th>
                                <th class="text-center">Tag Name</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>


        </div>
    </div>
    <!--/div-->
</div>
<!-- row closed -->

<script>

    $('#TagTable').DataTable(
    {
        "ajax":
        {
            "url": '@Url.Action("GetTagList", "Tags")',
            "type": "POST",
            "datatype": "json",
        },
        'columns':
            [
                { "data": "Action", "name": "" },
                { "data": "TagName", "name": "TagName" },
            ],
        'columnDefs':
            [
                {
                    "targets": 0,
                    'className': 'col-lg-1',
                    'searchable': false,
                    'orderable': false,
                    'sortable': false,
                    "render": function (data, type, full, meta) {
                            return '<div class="btn-group" role="group">' +
                                        '<a onclick="EditFunction(' + full.TagId + ')" class="btn btn-info" title="Edit"><i class="icon-pencil"></i></a> ' +
                                        '<a onclick="deleteFunction(' + full.TagId + ')" class="btn btn-danger" title="Delete" data-toggle="modal" data-target="#deleteModal"><i class="glyphicon glyphicon-floppy-remove"></i></a>' +
                                    '</div>';

                    }
                },
                {
                    "targets": 1,
                    'className': 'col-lg-2',
                    "render": function (data, type, full, meta) {
                        return full.TagName;
                    }
                },
            ],
        "serverSide": "true",
        "processing": "true",
        "language":
        {
            "processing": "<i class='icon-spinner spinner icon-3x'></i>",
            "search": "<span>Search :</span> _INPUT_",
            "searchPlaceholder": "Type to Filter",
            "lengthMenu": "<span>Show :</span> _MENU_",
            "paginate": { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
        },
    });

    function deleteFunction(id) {
        $("#TagDeleteId").val(id);
        $("#DeleteModal").modal('show');
    }

    function AddNew() {
        $("#AddNewModal").modal('show');
    }

    function EditFunction(id) {
        $.ajax({
            type: 'POST',
            url: "../Tags/TagById",
            dataType: "json",
            data: {
                Id: id
            },
            success: function (response) {
                $("#updId").val(response.Id);
                $("#updName").val(response.TagName);
                $("#UpdateModal").modal('show');
            },
            error: function () {
                alert("ajax Failed");
            }
        });
    }

</script>