Shiftbook/Controllers/TypeController.cs
using Shiftbook.BL;
using Shiftbook.Helping_Classes;
using Shiftbook.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Shiftbook.Controllers
{
    [ValidationFilter(Role = 12)]
    public class TypeController : Controller
    {
        DatabaseEntities db = new DatabaseEntities();
        GeneralPurpose gp = new GeneralPurpose();
        MailSender ms = new MailSender();
        private bool isLogedIn()
        {
            if (gp.ValidateLoggedinUser() != null)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        [Route("ViewTypes")]
        // GET: Type
        public ActionResult ViewTypes(string message = "", string color = "")
        {
            if (color == "red")
            {
                ViewBag.errormessage = message;
                ViewBag.color = color;
            }
            if (color == "green")
            {
                ViewBag.successfullmessage = message;
                ViewBag.color = color;
            }
            return View();
        }

        [HttpPost]
        public ActionResult GetTypesList()
        {
            List<Models.Type> list = new List<Models.Type>();
            if (gp.ValidateLoggedinUser().Role == 1 && gp.ValidateLoggedinUser().IsPrimary == 1)
            {
                list = new TypeBL().GetActiveTypesList(db).OrderByDescending(x => x.Id).ToList();
            }
            else
            {
                list = new TypeBL().GetActiveTypesList(db).Where(x => x.CreatedBy == gp.ValidateLoggedinUser().Id).OrderByDescending(x => x.Id).ToList();
            }

            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string searchValue = Request["search[value]"];
            string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            string sortDirection = Request["order[0][dir]"];

            if (sortColumnName != "" && sortColumnName != null)
            {
                if (sortDirection == "asc")
                {
                    list = list.OrderByDescending(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                }
                else
                {
                    list = list.OrderBy(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                }
            }

            if (!string.IsNullOrEmpty(searchValue))
            {
                list = list.Where(x => x.TypeName.ToLower().Contains(searchValue.ToLower())
                        ).ToList();
            }
            int totalrows = list.Count();
            int totalrowsafterfilterinig = list.Count();
            list = list.Skip(start).Take(length).ToList();

            List<DTO> udto = new List<DTO>();
            foreach (Models.Type u in list)
            {
                DTO obj = new DTO()
                {
                    TypeId = u.Id,
                    TypeEncId = GeneralPurpose.EncryptId(u.Id),
                    TypeName = u.TypeName,
                    Role = (int)gp.ValidateLoggedinUser().Role
                    
                };

                udto.Add(obj);
            }
            return Json(new { data = udto, draw = Request["draw"], recordsTotal = totalrows, recordsFiltered = totalrowsafterfilterinig }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PostAddNewType(Models.Type _Type, int PageId = -1)
        {
            if ((!isLogedIn()))
            {
                return RedirectToAction("Login", "Auth");
            }
            if (_Type.TypeName == null)
            {
                if (PageId == 2)
                {
                    return RedirectToAction("NewInventory", "Inventory", new { message = "Fill all The <strong>(*)</strong> Fields", color = "red" });
                }
                else
                {
                    return RedirectToAction("ViewTypes", new { message = "Fill all The <strong>(*)</strong> Fields", color = "red" });
                }
            }
            int count = new TypeBL().GetActiveTypesList(db).Where(x => x.IsActive == 1 && x.TypeName == _Type.TypeName).Count();
            if (count > 0)
            {
                if (PageId == 2)
                {
                    return RedirectToAction("NewInventory", "Inventory", new { message = "This Type Name is Already Registered", color = "red" });
                }
                else
                {
                    return RedirectToAction("ViewTypes", new { message = "This Type Name is Already Registered", color = "red" });
                }
            }

            Models.Type type = new Models.Type()
            {
                TypeName = _Type.TypeName,
                IsActive = 1,
                CreatedAt = GeneralPurpose.DateTimeNow(),
                CreatedBy = gp.ValidateLoggedinUser().Id
            };
            if (new TypeBL().AddType(type, db))
            {
                if (PageId == 2)
                {
                    return RedirectToAction("NewInventory", "Inventory", new { message = "Record is Added Successfully", color = "green" });
                }
                else
                {
                    return RedirectToAction("ViewTypes", new { message = "Record is Added Successfully", color = "green" });
                }
            }
            if (PageId == 2)
            {
                return RedirectToAction("NewInventory", "Inventory", new { message = "Record connot be added to database", color = "red" });
            }
            else
            {
                return RedirectToAction("ViewTypes", new { message = "Record connot be added to database", color = "red" });
            }
        }

        [HttpPost]
        public ActionResult TypeById(int Id = -1)
        {
            Models.Type _Type = new TypeBL().GetActiveTypeById(Id, db);
            if (_Type != null)
            {
                Models.Type sST = new Models.Type()
                {
                    Id = _Type.Id,
                    TypeName = _Type.TypeName,
                };
                return Json(sST, JsonRequestBehavior.AllowGet);
            }

            return Json(JsonRequestBehavior.AllowGet);
        }

        public ActionResult PostUpdate(Models.Type _Type)
        {
            int count = new TypeBL().GetActiveTypesList(db).Where(x => x.TypeName == _Type.TypeName && x.Id != _Type.Id).Count();
            if (count > 0)
            {
                return RedirectToAction("ViewTypes", new { message = "This Option is Already Registered", color = "red" });
            }
            Models.Type obj = new TypeBL().GetActiveTypeById(_Type.Id, db);

            obj.TypeName = _Type.TypeName;

            if (new TypeBL().UpdateType(obj, db))
            {
                return RedirectToAction("ViewTypes", new { message = "Record is Updated Successfully", color = "green" });
            }

            return RedirectToAction("ViewTypes", new { message = "Something is Wrong", color = "red" });
        }

        public ActionResult Delete(int id, string way = "")
        {
            Models.Type u = new TypeBL().GetActiveTypeById(id, db);
            if (u == null)
            {
                return RedirectToAction("ViewTypes", new { msg = "Record not found", color = "red", way = way });
            }

            if (new TypeBL().DeleteType(id, db))
            {
                return RedirectToAction("ViewTypes", new { msg = "Record deleted successfully", color = "green", way = way });
            }
            else
            {
                return RedirectToAction("ViewTypes", new { msg = "Something is wrong", color = "red", way = way });
            }
        }
    }
}

Shiftbook/Views/Type/ViewTypes.cshtml
@{
    ViewBag.Title = "ViewTypes";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<!--Add New Modal-->
<div class="modal fade" id="AddNewModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Add New Type</h3>
            </div>
            <form method="post" action="@Url.Action("PostAddNewType", "Type")">
                <div class="modal-body p-5">
                    <div class="col-md-12  m-10">
                        <div class="form-group">
                            <label class="control-label col-md-3 text-bold">Name <span class="text-danger">*</span></label>
                            <div class="col-md-9">
                                <input type="text" name="TypeName" class="form-control required" required="" placeholder="Electrical">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer pt-10">
                    <button type="button" class="btn btn-link" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Submit Form</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Modal-->
<div class="modal fade" id="DeleteModal">
    <div class="modal-dialog">
        <div class="modal-content text-center">
            <div class="modal-header bg-danger">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Warning</h3>
            </div>
            <form method="post" action="@Url.Action("Delete", "Type")">
                <div class="modal-body p-5">
                    <h6 class="text-semibold">
                        Do you really want to Delete this Type?<br />
                        This Type is going to permanently delete from our System.<br />
                        This Action Cannot be Undone.
                    </h6>
                    <input type="hidden" name="id" id="TypeDeleteId" />
                </div>
                <div class="modal-footer border-top-1 border-top-grey-800 pt-10">
                    <button type="button" class="btn btn-link" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Update Modal-->
<div class="modal fade" id="UpdateModal">
    <div class="modal-dialog">
        <div class="modal-content text-center">
            <div class="modal-header bg-success">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Update</h3>
            </div>
            <form method="post" action="@Url.Action("PostUpdate", "Type")">
                <div class="modal-body p-5">
                    <div class="col-md-12  m-10">
                        <input type="hidden" name="Id" id="updId" value="" />
                        <div class="form-group">
                            <label class="control-label col-md-3 text-bold">Name <span class="text-danger">*</span></label>
                            <div class="col-md-9">
                                <input type="text" name="TypeName" id="updName" class="form-control required" required="required" placeholder="Electrical">
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer pt-10">
                    <button type="button" class="btn btn-link" data-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-success">Submit Form</button>
                </div>
            </form>
        </div>
    </div>
</div>


<!--Form Modal-->
<!-- row -->
<div class="row row-sm ">
    <div class="row">
        <div class="col-lg-6 col-md-offset-3" id="ViewBagMessages">
            @if (ViewBag.successfullmessage != "" && ViewBag.successfullmessage != null)
            {
                <div class="alert alert-success alert-styled-left alert-arrow-left alert-bordered">
                    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
                    <span class="text-semibold">Complete!</span> @ViewBag.successfullmessage.
                </div>
            }
            @if (ViewBag.errormessage != "" && ViewBag.errormessage != null)
            {
                <div class="alert alert-danger alert-styled-left alert-bordered">
                    <button type="button" class="close" data-dismiss="alert"><span>×</span><span class="sr-only">Close</span></button>
                    <span class="text-semibold">Oh snap!</span> @ViewBag.errormessage <span class="alert-link">try submitting again</span>.
                </div>
            }
        </div>
    </div>

    <!--div-->
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-header pb-0 pt-10">
                <div class="d-flex text-center">
                    <h1 class=""><u>Type List</u></h1>
                    <i class="mdi mdi-dots-horizontal text-gray"></i>
                </div>
                <div class="row pt-20">
                    <div class="col-md-9 col-sm-12">
                        &nbsp;
                    </div>
                    <div class="col-md-2 col-sm-12 pull-right">
                        <button class="btn btn-primary" onclick="AddNew()">Add New Type</button>
                    </div>
                </div>
            </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table text-md-nowrap table-striped table-bordered text-center" id="TypeTable">
                        <thead class="bg-purple">
                            <tr>
                                <th class="text-center">Action</th>
                                <th class="text-center">Type Name</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>


        </div>
    </div>
    <!--/div-->
</div>
<!-- row closed -->

<script>

    $('#TypeTable').DataTable(
    {
        "ajax":
        {
            "url": '@Url.Action("GetTypesList", "Type")',
            "type": "POST",
            "datatype": "json",
        },
        'columns':
            [
                { "data": "Action", "name": "" },
                { "data": "TypeName", "name": "TypeName" },
            ],
        'columnDefs':
            [
                {
                    "targets": 0,
                    'className': 'col-lg-1',
                    'searchable': false,
                    'orderable': false,
                    "render": function (data, type, full, meta) {
                            return '<div class="btn-group" role="group">' +
                                        '<a onclick="EditFunction(' + full.TypeId + ')" class="btn btn-info" title="Edit"><i class="icon-pencil"></i></a> ' +
                                        '<a onclick="deleteFunction(' + full.TypeId + ')" class="btn btn-danger" title="Delete" data-toggle="modal" data-target="#deleteModal"><i class="glyphicon glyphicon-floppy-remove"></i></a>' +
                                    '</div>';

                    }
                },
                {
                    "targets": 1,
                    'className': 'col-lg-2',
                    "render": function (data, type, full, meta) {
                        return full.TypeName;
                    }
                },
            ],
        "serverSide": "true",
        "processing": "true",
        "language":
        {
            "processing": "<i class='icon-spinner spinner icon-3x'></i>",
            "search": "<span>Search :</span> _INPUT_",
            "searchPlaceholder": "Type to Filter",
            "lengthMenu": "<span>Show :</span> _MENU_",
            "paginate": { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
        },
    });

    function deleteFunction(id) {
        $("#TypeDeleteId").val(id);
        $("#DeleteModal").modal('show');
    }

    function AddNew() {
        $("#AddNewModal").modal('show');
    }

    function EditFunction(id) {
        $.ajax({
            type: 'POST',
            url: "../Type/TypeById",
            dataType: "json",
            data: {
                Id: id
            },
            success: function (response) {
                $("#updId").val(response.Id);
                $("#updName").val(response.TypeName);
                $("#UpdateModal").modal('show');
            },
            error: function () {
                alert("ajax Failed");
            }
        });
    }

</script>