Shiftbook/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Shiftbook.Models;
using Shiftbook.Helping_Classes;
using Shiftbook.BL;
using System.Text;

namespace Shiftbook.Controllers
{
    public class AjaxController : Controller
    {
        GeneralPurpose gp = new GeneralPurpose();
        DatabaseEntities de = new DatabaseEntities();

        #region User

        [HttpPost]
        public ActionResult GetUserDataTableList(string fName = "", string lName="", string email = "", int role = -1)
        {
            List<User> ulist = new UserBL().GetActiveUsersList(de).Where(x => x.IsPrimary != 1 ).ToList();

            if(gp.ValidateLoggedinUser().IsPrimary != 1)
            {
                ulist = ulist.Where(x => x.Role != 1).ToList();
            }

            if(fName != "")
            {
                ulist = ulist.Where(x => x.FName.ToLower().Contains(fName.ToLower())).ToList();
            }
            if (lName != "")
            {
                ulist = ulist.Where(x => x.LName.ToLower().Contains(lName.ToLower())).ToList();
            }
            if (email != "")
            {
                ulist = ulist.Where(x => x.Email.ToLower().Contains(email.ToLower())).ToList();
            }
            if (role != -1)
            {
                ulist = ulist.Where(x => x.Role == role).ToList();
            }

            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string searchValue = Request["search[value]"];
            string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            string sortDirection = Request["order[0][dir]"];

            if (sortColumnName != "" && sortColumnName != null)
            {
                if (sortColumnName != "0")
                {
                    if (sortDirection == "asc")
                    {
                        if (sortColumnName == "Department")
                        {
                            ulist = ulist.OrderByDescending(x => x.Department.Name).ToList();
                        }
                        else
                        {
                            ulist = ulist.OrderByDescending(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                        }
                    }
                    else
                    {
                        if (sortColumnName == "Department")
                        {
                            ulist = ulist.OrderBy(x => x.Department.Name).ToList();
                        }
                        else
                        {
                            ulist = ulist.OrderBy(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                        }
                    }
                }
            }

            int totalrows = ulist.Count();

            //filter
            if (!string.IsNullOrEmpty(searchValue))
            {
                ulist = ulist.Where(x => x.Email.ToLower().Contains(searchValue.ToLower()) ||
                                    x.FName.ToLower().Contains(searchValue.ToLower()) ||
                                    x.LName.ToLower().Contains(searchValue.ToLower()) ||
                                    (x.Contact != null && x.Contact.ToLower().Contains(searchValue.ToLower()))).ToList();
            }

            int totalrowsafterfilterinig = ulist.Count();


            // pagination
            ulist = ulist.Skip(start).Take(length).ToList();

            List<UserDTO> udto = new List<UserDTO>();

            foreach (User u in ulist)
            {
                UserDTO obj = new UserDTO()
                {
                    Id = u.Id,
                    EncId = GeneralPurpose.EncryptId(u.Id),
                    DepartmentId = (int)u.DepartmentId,
                    DepartmentName = u.Department.Name,
                    FName = u.FName,
                    LName = u.LName,
                    UserName = u.UserName,
                    Language = u.Language,
                    Contact = u.Contact,
                    Email = u.Email,
                    //Password = StringCipher.Decrypt(u.Password),
                    Author = u.Author==null?0:1,
                    Role = (int)u.Role
                };

                udto.Add(obj);
            }

            return Json(new { data = udto, draw = Request["draw"], recordsTotal = totalrows, recordsFiltered = totalrowsafterfilterinig }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult GetUserList(int role = -1)
        {
            List<User> uList = new UserBL().GetActiveUsersList(de).Where(x=> x.IsPrimary != 1).OrderBy(x=> x.FName).ToList();

            if(role == 1)
            {
                uList = uList.Where(x => x.Role == role).ToList();
            }
            if (role == 2)
            {
                uList = uList.Where(x => x.Role == role).ToList();
            }
            if (role == 3)
            {
                uList = uList.Where(x => x.Role == role).ToList();
            }
            if (role == 4)
            {
                uList = uList.Where(x => x.Role == role).ToList();
            }

            List<UserDTO> udto = new List<UserDTO>();
            string DepartmentName = "";
            foreach (User u in uList)
            {
                if(u.DepartmentId != null)
                {
                    DepartmentName = u.Department.Name;
                }
                else
                {
                    DepartmentName = "";
                }
                UserDTO obj = new UserDTO()
                {
                    Id = u.Id,
                    EncId = GeneralPurpose.EncryptId(u.Id),
                    DepartmentName = DepartmentName,
                    FName = u.FName + " " + u.LName,
                    UserRole = GeneralPurpose.GetUserRole((int)u.Role)
                };

                udto.Add(obj);
            }

            return new JsonResult()
            {
                Data = udto,
                ContentType = "application/json",
                ContentEncoding = Encoding.UTF8,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet,
                MaxJsonLength = Int32.MaxValue
            };
        }


        [HttpPost]
        public ActionResult GetUserById(int id)
        {
            User u = new UserBL().GetActiveUserById(id, de);
            if (u == null)
            {
                return Json(0, JsonRequestBehavior.AllowGet);
            }
            UserDTO obj = new UserDTO()
            {
                Id = u.Id,
                EncId = GeneralPurpose.EncryptId(u.Id),
                DepartmentId = (int)u.DepartmentId,
                DepartmentName = u.Department.Name,
                FName = u.FName,
                LName = u.LName,
                UserName = u.UserName,
                Language = u.Language,
                Contact = u.Contact,
                Email = u.Email,
                Password = StringCipher.Decrypt(u.Password),
                Author = u.Author==null? 0 : 1,
                Role = (int)u.Role
            };

            return Json(obj, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult ValidateEmail(string email, int id = -1)
        {
            return Json(gp.ValidateEmail(email, id), JsonRequestBehavior.AllowGet);
        }

        public bool CheckEmailValidity(string email)
        {
            var trimmedEmail = email.Trim();

            if (trimmedEmail.EndsWith("."))
            {
                return false; // suggested by @TK-421
            }
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == trimmedEmail;
            }
            catch
            {
                return false;
            }
        }

        #endregion

        #region Department

        [HttpPost]
        public ActionResult GetDepartmentDataTableList(string Name = "", string Location = "")
        {
            List<Department> list = new DepartmentBL().GetActiveDepartmentsList(de).ToList();

            if (Name != "")
            {
                list = list.Where(x => x.Name.ToLower().Contains(Name.ToLower())).ToList();
            }
            if (Location != "")
            {
                list = list.Where(x => x.Location != null).ToList();
                list = list.Where(x => x.Location.ToLower().Contains(Location.ToLower())).ToList();
            }

            int start = Convert.ToInt32(Request["start"]);
            int length = Convert.ToInt32(Request["length"]);
            string searchValue = Request["search[value]"];
            string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            string sortDirection = Request["order[0][dir]"];

            if (sortColumnName != "" && sortColumnName != null)
            {
                if (sortColumnName != "0")
                {
                    if (sortDirection == "asc")
                    {
                        list = list.OrderByDescending(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                    }
                    else
                    {
                        list = list.OrderBy(x => x.GetType().GetProperty(sortColumnName).GetValue(x)).ToList();
                    }
                }
            }

            int totalrows = list.Count();

            //filter
            if (!string.IsNullOrEmpty(searchValue))
            {
                list = list.Where(x => x.Name.ToLower().Contains(searchValue.ToLower()) ||
                                    x.Location.ToLower().Contains(searchValue.ToLower())
                                    ).ToList();
            }

            int totalrowsafterfilterinig = list.Count();

Shiftbook/Views/Admin/AddDepartment.cshtml
@{
    ViewBag.Title = "Add New Department";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}


<div class="p-20">

    <div class="row">
        <form action="@Url.Action("PostAddDepartment", "Admin")" method="post">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="panel panel-flat">
                        <div class="panel-heading">
                            <h2 class="panel-title text-center text-bold">New Department</h2>
                            <div class="text-center" id="alertMsg" style="color:@ViewBag.Color ; font-weight:bold">
                                @ViewBag.Message
                            </div>
                        </div>

                        <div class="panel-body">

                            <legend class="text-bold text-uppercase"><span class="text-danger">*</span> Fields are mandatory to fill</legend>
                            
                            <div class="form-group">
                                <label class="text-bold">Name <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" onkeyup="validateDepartment(this.value)" required name="Name" placeholder="Enter Department Name Here">
                                <span class="text-danger" id="depErrMsg"></span>
                            </div>

                            <div class="form-group">
                                <label class="text-bold">Location</label>
                                <input type="text" class="form-control" name="Location" placeholder="Enter Department Location Here">
                            </div>

                            
                            <div class="text-right">
                                <button type="submit" id="subBtn" class="btn btn-primary">Add <i class="icon-database-insert position-right"></i></button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </form>
    </div>

</div>

<script>

    function validateDepartment(name)
    {
        if (name != "")
        {
            $.ajax({
                type: 'POST',
                url: "../Ajax/ValidateDepartment",
                dataType: "json",
                data: {
                    name: name, id: -1
                },
                success: function (response)
                {
                    if (response == true)
                    {
                        $('#depErrMsg').text("");
                        $('#subBtn').attr('disabled', false);
                    }
                    else {
                        $('#depErrMsg').text("Duplicate Name");
                        $('#subBtn').attr('disabled', true);
                    }
                },
                error: function ()
                {
                    $('#depErrMsg').text("");
                    $('#subBtn').attr('disabled', false);

                    alert("Department validation ajax failed");
                }
            });
        }

    }
</script>

Shiftbook/Views/Admin/CodeHistory.cshtml
@{
    ViewBag.Title = "CodeHistory";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<img id="loadImg" src='../Content/assets/images/loading.gif' width='150' style="position:fixed; margin-top:20%; margin-left:35%; z-index:111; display:none" />

<div class="panel p-20 m-10">

    <div class="row text-center">
        <h3><u>Equipment Code History</u></h3>

        <div class="text-bold" style="color:@ViewBag.Color;" id="alertMsg">
            @ViewBag.Message
        </div>
        <input type="hidden" id="CodeId" value="@ViewBag.History.Id" />
        <div class="col-md-4 col-md-offset-4 col-sm-12">
            <h3>Equipment Code: <span>@ViewBag.History.Code</span></h3>
        </div>
    </div>


    <div class="table-responsive">
        <table class="table text-md-nowrap table-striped table-bordered text-center no-footer" id="codeTable">
            <thead class="bg-indigo">
                <tr>
                    <th class="text-bold text-center">
                        Status
                    </th>
                    <th class="text-bold text-center">
                       Added By
                    </th>
                    <th class="text-bold text-center">
                        Date/Time
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>

<script>
    var Id = $('#CodeId').val();
    loadTable();
    function loadTable(Name, Location)
    {
        $('#codeTable').DataTable(
        {
            "ajax":
            {
                "url": '@Url.Action("GetEquipmentCodeHistory", "Ajax")',
                "type": "POST",
                "datatype": "json",
                "data": {
                    id: Id
                }
            },
            'columns':
            [
                //{ "data": "Action", "name": "0" },
                { "data": "HStatus", "name": "Status" },
                { "data": "HCreated", "name": "User" },
                { "data": "HCreatedAt", "name": "CreatedAt" },
            ],
            'columnDefs':
            [
                //{
                //    "targets": 0,
                //    'className': 'col-md-4',
                //    'sortable': false,
                //    "render": function (data, type, full, meta)
                //    {
                //        return '<div class="btn-group" role="group">' +
                //            '<a onclick="updateFunction(' + full.Id + ')" class="btn btn-info" title="Edit"><i class="icon-pencil"></i></a> ' +
                //            '<a href="../Admin/History?Id=' + full.Id + '" class="btn btn-success" title="History"><i class="icon-eye2"></i></a> ' +
                //            '<a onclick="deleteFunction(' + full.Id + ')" class="btn btn-danger" title="Delete" data-toggle="modal" data-target="#deleteModal"><i class="glyphicon glyphicon-floppy-remove"></i></a>' +
                //            '</div>';
                //    }
                //},
                {
                    "targets": 0,
                    'className': 'col-md-4',
                    "render": function (data, type, full, meta)
                    {
                        if ($.trim(full.HStatus) == "") {
                            return '<span class="text-danger">---</span>';
                        }
                        else {
                            return full.HStatus;
                        }
                    }
                },
                {
                    "targets": 1,
                    'className': 'col-md-4',
                    "render": function (data, type, full, meta)
                    {
                        if ($.trim(full.HCreated) == "") {
                            return '<span class="text-danger">---</span>';
                        }
                        else {
                            return full.HCreated;
                        }
                    }
                },
                {
                    "targets": 2,
                    'className': 'col-md-4',
                    "render": function (data, type, full, meta) {
                        if ($.trim(full.HCreatedAt) == "")
                        {
                            return '<span class="text-danger">---</span>';
                        }
                        else
                        {
                            return full.HCreatedAt;
                        }
                    }
                },
            ],
            "serverSide": "true",
            "processing": "true",
            "language":
            {
                "processing": "<i class='icon-spinner spinner icon-2x'></i>",
                "search": "<span>Search :</span> _INPUT_",
                "searchPlaceholder": "Filter",
                "lengthMenu": "<span>Show :</span> _MENU_",
                "paginate": { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
            },
        });
    }
</script>

Shiftbook/Views/Admin/ViewDepartments.cshtml
@{
    ViewBag.Title = "View Departments";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<style>
    .table > tbody > tr > td {
        padding: 5px !important;
    }
</style>

<img id="loadImg" src='../Content/assets/images/loading.gif' width='150' style="position:fixed; margin-top:20%; margin-left:35%; z-index:111; display:none" />

<div class="modal fade" id="deleteModal">
    <div class="modal-dialog">
        <div class="modal-content text-center">
            <div class="modal-header bg-danger">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h3 class="modal-title">Warning</h3>
            </div>
            <div class="modal-body p-5">
                <h6 class="text-semibold">
                    Do you really want to Delete this?<br />
                    This is going to permanently delete from our System.<br />
                    This Action Cannot be Undone.
                </h6>
                <input type="hidden" name="id" id="TypeDeleteId" />
            </div>
            <div class="modal-footer border-top-1 border-top-grey-800 pt-10">
                <button type="button" class="btn btn-link" data-dismiss="modal">No</button>
                <a class="btn btn-danger" id="deleteId">Delete</a>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="updateModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <h4 class="text-center text-bold">Update Department</h4>
                <button type="button" class="close text-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body">
                <form class="form-horizontal" action="@Url.Action("PostUpdateDepartment","Admin")" method="post">

                    <input type="hidden" name="Id" id="updId" />
                    <input type="hidden" name="way" value="@ViewBag.Way" />


                    <div class="form-group">
                        <label class="text-bold">Name <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" required name="Name" id="updName" placeholder="Enter First Name" onkeyup="validateDepartment(this.value)">
                        <span class="text-danger" id="updDepartmentErrMsg"></span>
                    </div>

                    <div class="form-group">
                        <label class="text-bold">Location</label>
                        <input type="text" class="form-control" name="Location" id="updLocation" placeholder="Enter Location">
                    </div>

                    <div class="modal-footer">
                        <button type="submit" value="submit" class="btn btn-primary" id="updSubBtn">Update</button>
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat text-black">
                <div class="panel-heading" style="background: #e8eced ">
                    <h2 class="text-center text-black">
                        Search
                    </h2>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li><a data-action="collapse" class="rotate-180"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body pt-20 pb-20" style="display:none">
                    <div class="row">
                        <div class="col-md-4 col-lg-4">
                            <div class="form-group">
                                <label><strong>Name:</strong></label>
                                <input type="text" placeholder="" class="form-control" id="searchName">
                            </div>
                        </div>

                        <div class="col-md-4 col-lg-4">
                            <div class="form-group">
                                <label><strong>Location:</strong></label>
                                <input type="text" placeholder="" class="form-control" id="searchLocation">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <button onclick="clearSearch()" class="btn btn-danger btn-block">Reset</button><br />
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 col-xs-12"></div>

                        <div class="col-md-3 col-sm-12 col-xs-12">
                            <div class="form-group text-right">
                                <button onclick="searchTable()" class="btn btn-success btn-block">Search</button><br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12">
            <div class="panel p-20">
                <div class="row text-center">
                    <h3><u>Department List</u></h3>
                    <div class="text-bold" style="color:@ViewBag.Color;" id="alertMsg">
                        @ViewBag.Message
                    </div>
                </div>

                <div class="row mb-10">
                    <div class="col-md-8"></div>
                    <div class="col-md-2 pull-right">
                        <a href="@Url.Action("AddDepartment","Admin")" class="btn btn-primary btn-block pull-right">Add New</a>
                    </div>
                </div>

                <input type="hidden" id="way" value="@ViewBag.Way" />
                <div class="table-responsive">
                    <table class="table text-md-nowrap table-striped table-bordered text-center no-footer" id="departmentTable">
                        <thead class="bg-indigo">
                            <tr>
                                <th hidden>...</th>
                                <th class="text-bold text-center" style="min-width:200px">
                                    Action
                                </th>
                                <th class="text-bold text-center">
                                    Name
                                </th>
                                <th class="text-bold text-center">
                                    Location
                                </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var way = $('#way').val();

    loadTable();

    function loadTable(Name, Location)
    {
        $('#departmentTable').DataTable(
        {
            "ajax":
            {
                "url": '@Url.Action("GetDepartmentDataTableList", "Ajax")',
                "type": "POST",
                "datatype": "json",
                "data": { Name: Name, Location: Location}
            },
            'columns':
            [
                { "data": "Hidden", "name": "0" },
                { "data": "Action", "name": "0" },
                { "data": "Name", "name": "Name" },
                { "data": "Location", "name": "Location" },
            ],
            'columnDefs':
            [
                {
                    "targets": 0,
                    "visible": false,
                    "searchable": false,
                    "render": function (data, type, full, meta) {
                        return null;
                    }
                },
                {
                    "targets": 1,
                    'className': 'col-md-4',
                    'sortable': false,
                    "render": function (data, type, full, meta)
                    {
                        return '<div class="btn-group" role="group">' +
                            '<a onclick="updateFunction(' + full.Id + ')" class="btn btn-info" title="Edit"><i class="icon-pencil"></i></a> ' +
                            '<a onclick="deleteFunction(' + full.Id + ')" class="btn btn-danger" title="Delete" data-toggle="modal" data-target="#deleteModal"><i class="glyphicon glyphicon-floppy-remove"></i></a>' +
                            '</div>';
                    }
                },
                {
                    "targets": 2,
                    'className': 'col-md-4',
                    "render": function (data, type, full, meta)
                    {
                        return full.Name ;
                    }
                },
                {
                    "targets": 3,
                    'className': 'col-md-4',
                    "render": function (data, type, full, meta)
                    {
                        if ($.trim(full.Location) == "") {
                            return '<span class="text-danger">---</span>';
                        }
                        else {
                        return full.Location ;
                        }
                    }
                },
            ],
            "serverSide": "true",
            "processing": "true",
            "language":
            {
                "processing": "<i class='icon-spinner spinner icon-2x'></i>",
                "search": "<span>Search :</span> _INPUT_",
                "searchPlaceholder": "Filter",
                "lengthMenu": "<span>Show :</span> _MENU_",
                "paginate": { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
            },
        });
    }

    function searchTable()
    {
        var Name = $('#searchName').val();
        var Location = $('#searchLocation').val();

        $('#departmentTable').DataTable().clear();
        $('#departmentTable').DataTable().destroy();

        loadTable(Name, Location);
    }

    function toggleSearch() {
        if ($('#searchIcon').hasClass('icon-search4')) {
            $('#searchIcon').removeClass('icon-search4');
            $('#searchIcon').removeClass('text-info');
            $('#searchIcon').addClass('icon-cross2');
            $('#searchIcon').addClass('text-danger');

            $('#searchDiv').toggle('show');
        }
        else {
            $('#searchIcon').addClass('icon-search4');
            $('#searchIcon').addClass('text-info');
            $('#searchIcon').removeClass('icon-cross2');
            $('#searchIcon').removeClass('text-danger');

            $('#searchDiv').toggle('hide');
        }
    }

    function clearSearch()
    {
        $('#departmentTable').DataTable().clear();
        $('#departmentTable').DataTable().destroy();

        $('#searchName').val("");
        $('#searchLocation').val("");
        loadTable();
    }

    function updateFunction(id)
    {
        $('#updEmailErrMsg').text("");
        $('#updSubBtn').attr('disabled', false);

        $("#loadImg").show();

        $.ajax({
            type: 'POST',
            url: "../Ajax/GetDepartmentById",
            dataType: "json",
            data: {
                id: id
            },
            success: function (response)
            {
                if (response == 0) {
                    alert("Record not found");
                    location.reload();
                }

                $("#updId").val(response.Id);

                $("#updName").val(response.Name);
                $("#updLocation").val(response.Location);

                $("#loadImg").hide();
                $("#updateModal").modal('show');
            },
            error: function ()
            {
                $("#loadImg").hide();

                alert("ajax Failed");
            }
        });

    }

    function validateDepartment(name)
    {
        var id = $('#updId').val();
        if (name != "" && id != "")
        {
            $.ajax({
                type: 'POST',
                url: "../Ajax/ValidateDepartment",
                dataType: "json",
                data: {
                    name: name, id: id
                },
                success: function (response)
                {
                    if (response == true)
                    {
                        $('#updDepartmentErrMsg').text("");
                        $('#updSubBtn').attr('disabled', false);
                    }
                    else {
                        $('#updDepartmentErrMsg').text("Duplicate Name");
                        $('#updSubBtn').attr('disabled', true);
                    }
                },
                error: function ()
                {
                    $('#updDepartmentErrMsg').text("");
                    $('#updSubBtn').attr('disabled', false);

                    alert("Ajax failed");
                }
            });
        }

    }

    function deleteFunction(id) {
        var a = document.getElementById('deleteId');
        a.href = "../Admin/DeleteDepartment?id=" + id + "&way=@ViewBag.Way";
    }

</script>